# Generated by Django 6.0.1 on 2026-02-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varitaion_value',
            new_name='variation_value',
        ),
    ]
