# Generated by Django 6.0.1 on 2026-02-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
